### ISSUE TITLE
Error: "secure random number generation not supported by this browser"

### ISSUE THREAD

**Issue by LouisWayne** [EOSIO/eosjs-keygen#14]
Sorry for noob question here, but I want to know how I use this library.

So I ran the command:
```
// Install library
git clone https://github.com/EOSIO/eosjs-keygen.git
cd eosjs-keygen
npm install
npm run build

// Then go to the `dist` directory
cd dist

// And run the compiled JS file
node eosjs-keygen
```

After I ran this code, an error popped up:
```
C:\eosjs-keygen-master\dist\eosjs-keygen.js:18594
  throw new Error('secure random number generation not supported by this browser\nuse chrome, FireFox or Internet Explorer 11')
  ^

Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11
    at oldBrowser (C:\eosjs-keygen-master\dist\eosjs-keygen.js:18594:9)
    at Object.<anonymous> (C:\eosjs-keygen-master\dist\eosjs-keygen.js:13352:28)
    at Object.62../hash (C:\eosjs-keygen-master\dist\eosjs-keygen.js:13595:4)
    at s (C:\eosjs-keygen-master\dist\eosjs-keygen.js:1:679)
    at C:\eosjs-keygen-master\dist\eosjs-keygen.js:1:730
    at Object.<anonymous> (C:\eosjs-keygen-master\dist\eosjs-keygen.js:13170:16)
    at Object.61../hash (C:\eosjs-keygen-master\dist\eosjs-keygen.js:13325:4)
    at s (C:\eosjs-keygen-master\dist\eosjs-keygen.js:1:679)
    at C:\eosjs-keygen-master\dist\eosjs-keygen.js:1:730
    at Object.<anonymous> (C:\eosjs-keygen-master\dist\eosjs-keygen.js:11966:17)
```

Please help :D

**Comment by ekkis** [comment]
@LouisWayne I see you reported this close to 6 months ago and no one has addressed it.  did you figure out a solution?

**Comment by LouisWayne** [comment]
@ekkis Yes - I have fixed the issue, thanks!

**Comment by ekkis** [comment]
what did you do?

**Comment by LouisWayne** [comment]
@ekkis I believe I was using Windows (Windows 8.1 that is). Once I switched to Ubuntu, it didn't throw any error message.

**Comment by roppa** [comment]
I'm getting this error using sapper and webpack
