### ISSUE TITLE
sample code fails

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [EOSIO/eosjs-keygen#7]
code from readme fails with error: 
```
api error =>  https://t1readonly.eos.io/v1/chain/get_account {"account_name":"myaccount1231548489"}
{ FetchError: request to https://t1readonly.eos.io/v1/chain/get_account failed, reason: connect ETIMEDOUT 35.164.81.64:443
    at ClientRequest.<anonymous> (/Users/info/_sites/eos/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://t1readonly.eos.io/v1/chain/get_account failed, reason: connect ETIMEDOUT 35.164.81.64:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
{ FetchError: request to https://t1readonly.eos.io/v1/chain/get_account failed, reason: connect ETIMEDOUT 35.164.81.64:443
    at ClientRequest.<anonymous> (/Users/info/_sites/eos/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://t1readonly.eos.io/v1/chain/get_account failed, reason: connect ETIMEDOUT 35.164.81.64:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
Error:  { FetchError: request to https://t1readonly.eos.io/v1/chain/get_account failed, reason: connect ETIMEDOUT 35.164.81.64:443
    at ClientRequest.<anonymous> (/Users/info/_sites/eos/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://t1readonly.eos.io/v1/chain/get_account failed, reason: connect ETIMEDOUT 35.164.81.64:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
```

**Comment by Vasiliy-Bondarenko** [comment]
Ok. And how do i use my local node?
And why is it required at all?

**Comment by jcalfee** [comment]
This looks pretty cool:  http://dev.cryptolions.io/

discussion: https://forums.eosgo.io/discussion/493/jungle-testnet

I'm looking for a URL that we can put into `config.httpEndpoint`...
